# Generated by Django 5.1.4 on 2024-12-13 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ("status", "-created_at")},
        ),
    ]
