# Generated by Django 5.1.4 on 2024-12-14 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_rename_task_task_title_task_desc_task_notify_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="desc",
            new_name="description",
        ),
    ]
